### ISSUE TITLE
Dynamic Aurelia dependencies

### ISSUE THREAD

**Issue by jods4** [aurelia/pal#21] opened 2017-01-13 21:59 UTC
This is a meta-issue to track progress across all Aurelia repos.

In #17 it was decided that using `PLATFORM.moduleName()`, exported from `aurelia-pal` was the way to document dynamic dependencies consumed by the aurelia loader. 
The function has been added with da92298.

To follow up on that, it must now be used in every aurelia module that has dynamic imports.
Here's a checklist of _all_ modules to track progress, most probably don't need any change at all:
- [x] animator-css
- [x] animator-velocity
- [x] binding
- [x] bootstrapper
- [x] cache
- [x] dependency-injection
- [x] dialog
- [x] event-aggregator
- [x] fetch-client
- [x] framework
- [x] history
- [x] history-browser
- [x] hot-module-reload
- [x] html-import-template-loader
- [x] http-client
- [x] i18n
- [x] loader
- [x] loader-default
- [x] loader-nodejs
- [x] loader-webpack
- [x] logging
- [x] logging-console
- [x] metadata
- [x] pal
- [x] pal-browser
- [x] pal-nodejs
- [x] pal-worker
- [x] protractor-plugin
- [x] route-recognizer
- [x] router
- [ ] skeleton-plugin
- [x] task-queue
- [x] templating
- [x] templating-binding
- [x] templating-resources
- [x] templating-router
- [x] testing
- [ ] ui-virtualization
- [x] ux
- [x] validation
- [ ] web-components

Question: was the work with `aurelia.build.resources` complete? I.e. if there is no such key in `package.json`, can I assume the library doesn't need to be modified?

For now I think it's better to keep the `aurelia.build.resources` in place, in order to _not_ break existing tools. But once this is in place a deprecation is probably in order, with removal at a later stage.

CC: @niieani @EisenbergEffect

**Comment by EisenbergEffect** [comment] 2017-01-14 09:18
The main location is going to be the bootstrapper, I think.

**Comment by niieani** [comment] 2017-01-14 09:49
Regarding your question, I think we took a shortcut in that we put most of the `aurelia.build.resources` in the bootstrapper package, instead of the respective packages. There aren't many dynamic requires throughout Aurelia, so this should be a pretty simple task.

**Comment by jods4** [comment] 2017-01-14 20:22
I managed to get my demos running _without_ using `aurelia.build.resources`. I did not modify aurelia modules yet, instead I used a plugin of mine to introduce the dependencies I wanted in my build, like so:
```js
new ModuleDependenciesPlugin({
      "aurelia-bootstrapper": [ 
        // "aurelia-loader-webpack",    // detected by webpack itself
        "aurelia-pal-browser", 
        "aurelia-framework", 
      ],
      "aurelia-framework": [
        "aurelia-history-browser",
        "aurelia-logging-console", 
        "aurelia-templating-binding",
        "aurelia-templating-resources",
        "aurelia-templating-router",
        "aurelia-event-aggregator",
      ],
      "aurelia-templating-resources": [
        "./compose",
        "./if",
        "./with",
        // [...] some more skipped for brievity
      ],
      "aurelia-templating-router": [
        "./router-view",
        "./route-href",
      ],
    })
```

Most of it will be trivial enough, e.g. `templating-resources` or `templating-router`. 

But I think we need to have chat about `bootstrapper` and `framework`. The culprit is that those dynamic loads may not occur, depending on your configuration or your environment. And we most certainly don't want to embed those dependencies in the build if they are not used. For instance, I only listed one of the three PALs.

**Comment by niieani** [comment] 2017-01-15 08:34
I don't think there's any use case for having more than one PAL bundled. In some cases you might want to have a separate bundle for `pal-worker`, but it would still only contain that one PAL.

**Comment by jods4** [comment] 2017-01-15 10:10
@niieani Yes, that's what I'm saying. But the problem is that choosing which one is included must be done at build time and can't be declared inside `aurelia-bootstrapper`.

My thinking for `aurelia-bootstrapper` is: 
- the convoluted syntax used to import `aurelia-loader-webpack` is automatically picked up -> no change;
- the PAL must be decided by the build tool and should not be wrapped with `moduleName`;
- `aurelia-framework` is normal, should be wrapped with `moduleName`.

For `aurelia-framework` the problem is that all six modules are standard but optional configs. If I wrap them with `moduleName` everything will work but someone using `basicConfiguration()` instead of `standardConfiguration` will not want the router in the bundle.

Thoughts?

**Comment by jods4** [comment] 2017-01-15 14:05
What is `bootstrapper-webpack`? 
Despite its name I don't use it in my webpack builds...

**Comment by niieani** [comment] 2017-01-17 18:06
@jods4 `bootstrapper-webpack` was the webpack-specific bootstrapper code, which we will be deprecating soon, because we managed to get together a universal `aurelia-bootstrapper` with build-system detection for all our use cases (hence the "convoluted syntax" - its the only one that does not trip up SystemJS, RequireJS and works with Webpack when needed by not adding extraneous dependencies).

Your thinking is correct.

Not sure how to solve the `basicConfiguration()` vs `standardConfiguration()`. I've been thinking about this too some time ago, but dropped the matter as most users use `standardConfiguration` anyway. But it would be good to have this configurable.

**Comment by jods4** [comment] 2017-01-17 21:12
> Not sure how to solve the basicConfiguration() vs standardConfiguration(). I've been thinking about this too some time ago, but dropped the matter as most users use standardConfiguration anyway. But it would be good to have this configurable.

From the discussion with @EisenbergEffect, I won't add `moduleNames` for basic configurations. Rather, the build tooling will propose equivalent default configs that you can pick from.
The default will include everything so that it "just works", and then people can remove pieces that they don't use if they want a minimal size.

A "custom" configuration happens in user code, which means `moduleName`.

**Comment by niieani** [comment] 2017-01-18 10:05
Sounds good.

**Comment by jods4** [comment] 2017-01-19 02:30
OK, I have 4 PR open referencing this request. 
As you can see in the checklist this covers all "core" aurelia modules and is enough to be able to build an app that doesn't use optional modules without any extra manual dependencies.

(well, considering that the default extra dependencies are added by the build tool, as described above)

**Comment by niieani** [comment] 2017-01-19 19:32
Reviewed all. Great comment work, looking good to me!

**Comment by jods4** [comment] 2017-01-20 00:26
Thanks @niieani, can someone merge them? They're relatively trivial.

@EisenbergEffect I've looked at almost all modules (see the checklist). Would be nice to get help for the remaining ones.
I am pretty sure the following modules need changes:
- `dialog`
- `validation`
- `html-import-template-loader` (it fetches `webcomponentsjs/HTMLImport.min` through the loader).

For the rest I don't know.

**Comment by jods4** [comment] 2017-02-05 00:43
@EisenbergEffect I see that you are merging all my PR above and about to publish the new webpack tools.
It would be awsome if some Aurelia members could have a quick look and test with the items in this list that are not ticked yet.

Some might require no change at all, some might not work out of the box.

**Comment by niieani** [comment] 2017-02-05 11:09
There's a problem with `dialog` (and possibly with other external plugins) that is a bit harder to solve. See [this part of the code](https://github.com/aurelia/dialog/blob/22022bd8d25ae488d45566f509378a8813aeef7a/src/dialog-service.js#L111).

This is currently causing errors such as https://github.com/aurelia/dialog/issues/203.

In short, everything works as far as you provide a string path to the ViewModel and let Aurelia load it, rather than passing an actual class. The problem is that the Origin is set by Aurelia [whenever a module is being loaded](https://github.com/aurelia/loader-webpack/blob/master/src/aurelia-loader-webpack.ts#L203) by the `loader-webpack`, [unless it was in Webpack cache](https://github.com/aurelia/loader-webpack/blob/master/src/aurelia-loader-webpack.ts#L90-L100) before `eachModule` is executed. However if you `import` a class directly, Aurelia will have no knowledge of the file that it came from. For reference, the Origin is the reverse-map of exports to moduleIds, used to "guess" things like the path to the related View using a convention, so this problem is not specific to Dialog, but to all the times an Origin is expected but the underlying module has not yet been touched by the Loader.

This is also the reason my original v2 Webpack solution was naming all the Webpack modules, as opposed to the @jods4 re-written solution which only names those specifically referenced by `PLATFORM.moduleName`. This is what used to happen in v1 and leads to problems like https://github.com/aurelia/dialog/issues/241.

One semi-solution that comes to my mind would be to hook Webpack's chunking mechanism to run the Origin setter right after loading a given chunk. This would only work if all the modules had actual names, since it actually concatenates moduleId + `.html`, hence the above problem of `Cannot find module './76.html'`. The big downside of this is that all the modules in the whole chunk would get evaluated immediately, as if they're all imported, just so we can set their Origin.

Another two solutions would be breaking changes, but overall reduce complexity in some ways:

1. instruct users to user `PLATFORM.moduleName` even for ViewModels imported with `import {}` syntax if they plan on using them this way, while at the same time add logic to PLATFORM.moduleName which runs the `ensureOriginOnExports` logic on all the referenced modules. Not great.
1. disallow passing imported ViewModel classes directly, ask users to always specify paths as strings so they go through the loader. Simplest, but breaking users and plugins.

Any better ideas?

**Comment by StrahilKazlachev** [comment] 2017-02-05 11:50
@niieani So passing VM instance is also ok since it was already loaded?

**Comment by niieani** [comment] 2017-02-05 13:58
@StrahilKazlachev if it was loaded by Aurelia, and not via an `import`, it is ok currently, and will be okay with v2 of Webpack stack.

**Comment by jods4** [comment] 2017-02-05 15:03
@niieani I think we need to chat live about this.

To find the view, using `@useView` should be a work-around, right?

But the whole Origin thing is surely going to be broken for all classes that are not loaded through `aurelia-loader`.

**Comment by niieani** [comment] 2017-02-05 15:58
Yeah, explicitly decorating the ViewModel with `@useView` does work; not depending on the conventionally named views solves this. But currently the experience is sub-par, since it's that "sometimes" it works automatically, and sometimes it does not, and the user has no idea why.

Still, one of the nice things about Aurelia is that you don't need to use `useView` explicitly for every ViewModel.

I'm open to chatting about this on Gitter. 

Thoughts about this one, @EisenbergEffect? This is a problem especially with code loaded on demand, since even if we consider re-running `PAL.everyModule` with each new file, we would also evaluate all the modules inside it, as it loads. Not sure how is this solved in RJS or SystemJS (do we even support loading modules on demand in the latter?), unless its not, and we just missed a bug?

This is also one of the blockers that keeps us from implementing logic that replaces moduleNames with random names for security, since it simply tries to append `.html` to the end.

**Comment by niieani** [comment] 2017-02-05 16:14
The situation is even worse with SystemJS since there's no logic at all there. 
Reference logic for `eachModule` under RJS and SystemJS [here](https://github.com/aurelia/loader-default/blob/master/src/index.js#L122-L131).

Having just looked at the [implementation of Origin](https://github.com/aurelia/metadata/blob/master/src/origin.js#L38), it seems that when origin is undefined, it is to be retrieved and set _on demand_, as the `get` call occurs. Having said that, there might be a less-then-perfect way to do this with Webpack, since we know for sure a module should be in the Webpack cache once any `import`s have occured, we could just iterate over the whole cache and all of the keys of each element until we have found a matching function/class. The performance of this operation would be pretty bad though, however, if it's any consolation, this operation would only have to happen once (per each undefined Origin). With @jods4 approach of only naming modules which have been explicitly added via `PLATFORM.moduleName`, the user would still need to re-declare the imported file with a call to that function. If we renamed all modules as in my approach, the `import`s should work automatically.

Another thing is that our NodeJS loader will behave the same way as Webpack currently does (i.e. errors related to this will happen), since as far as I know there is no way to find out the file path from an already loaded reference to a function/class, and since there is no bundling involved here, running `eachModule` equivalent to set Origin for all `js` files under the root directory is probably out of the question (startup performance would be abysmal). Perhaps we could use some hacky node APIs to list all cached modules, but these APIs are explicitly defined as unsupported/deprecated in the NodeJS documentation, so even if we solve the Webpack problem somehow, I'm not sure how we'd do this for Node, and we'll need to support it if we want server-side-loading, going forward.

**Comment by jods4** [comment] 2017-02-15 09:31
@niieani 
Trying to make some progress here:
- I think you made protractor work with the new build, can I check it?
- Now that I added support to preserve the name of modules that are vm of views by convention, is `aurelia-dialog` ok?

@EisenbergEffect 
Is `html-import-template-loader` still a thing? I vaguely remember using this when I got started with Aurelia a long while ago but never using it since then... What does it do? Should I remove it from the list?

**Comment by niieani** [comment] 2017-02-15 17:45
@jods4 protractor is good since the updates that made it execute scripts synchronously. Don't remember if we published that to NPM yet or not.

Haven't retested `aurelia-dialog`  yet.

**Comment by jods4** [comment] 2017-02-15 17:46
Checking protractor. Doesn't matter if it's published yet, just want to make sure we have everything covered.

**Comment by jods4** [comment] 2017-02-15 18:07
Just spent some time with user mike-suggit who got his tests with Karma + Jasmine + aurelia-testing + Protractor working.

Was a bit rough because he had quite a few bad configs from existing build. But once everything was referencing the correct packages, the config properly updated, `moduleName` added where required, it all worked.

So although I did not look at it, I'm going to check that `aurelia-testing` checkbox.

**Comment by jdanyow** [comment] 2017-02-23 15:30
@jods4 - can you check validation off please- I've made the platform changes but I don't have privileges to update issues in this repo. Thanks!

**Comment by jods4** [comment] 2017-02-23 15:46
Thanks, I checked `validation` off the list.

**Comment by niieani** [comment] 2017-04-28 12:24
@jods4 could you share how you and **mike-suggit** configured karma to work with `aurelia-testing`?

**Comment by jods4** [comment] 2017-04-28 12:29
I don't remember, better ask @mike-suggitt directly!

**Comment by khuongduybui** [comment] 2017-08-23 21:28
It doesn't load aurelia-ux due to the ${$design} interpolation inside .css files.

**Comment by jods4** [comment] 2017-08-24 19:56
@khuongduybui I don't think this thread is the right place, you should file an issue in `aurelia-ux` repo.

This meta-issue is to keep track of where `PLATFORM.moduleName` were added in core aurelia libraries.

What you have sounds like a loader issue and should be tracked separately.

**Comment by khuongduybui** [comment] 2017-08-24 20:34
Ah okay, thanks. I'll file the issue in ux repo instead.

**Comment by bigopon** [comment] 2017-12-09 08:23
@jods4 the `html-import-template-loader` module doesn't seem to need it. I think it can be ticked.

**Comment by jods4** [comment] 2017-12-10 22:31
@bigopon Thanks for that! I checked it.

**Comment by Alexander-Taran** [comment] 2018-03-03 15:50
Et alors?
(-:

something about sprinkling moduleName all over the place
just a ping. seems almost baked.

**Comment by EisenbergEffect** [comment] 2018-03-03 21:52
Closing since I think all libs that require this have been instrumented.

**Closed as completed by EisenbergEffect** 2018-03-03 21:52 UTC
Labels: enhancement
